services:
  - type: web
    name: flask-app
    env: python
    region: oregon
    plan: free 
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: POCKETBASE_URL
        value: http://localhost:8090

  - type: web
    name: pocketbase
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: ./pocketbase serve --http 0.0.0.0:8090

  - type: worker
    name: dual-process
    startCommand: |
      gunicorn -w 2 app:app -b 0.0.0.0:8080 &
      ./pocketbase serve --http 0.0.0.0:8090
