services:
  - type: web
    name: flask-and-pocketbase
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      gunicorn app:app &
      ./pocketbase serve
    envVars:
      - key: FLASK_ENV
        value: production
