// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdminLoginLogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://127.0.0.1:5000/login"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void adminLoginLogout() {
    // Test name: Admin-Login-Logout
    // Step # | name | target | value
    // 1 | open | /login | 
    driver.get("http://127.0.0.1:5000/login");
    // 2 | setWindowSize | 650x696 | 
    driver.manage().window().setSize(new Dimension(650, 696));
    // 3 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 4 | type | id=email | kkglovemy@gmail.com
    driver.findElement(By.id("email")).sendKeys("kkglovemy@gmail.com");
    // 5 | type | id=password | password1234
    driver.findElement(By.id("password")).sendKeys("password1234");
    // 6 | click | css=.login-button | 
    driver.findElement(By.cssSelector(".login-button")).click();
    // 7 | click | linkText=Dashboard | 
    driver.findElement(By.linkText("Dashboard")).click();
    // 8 | click | css=.menu:nth-child(1) > ul > li:nth-child(2) > a > .text | 
    driver.findElement(By.cssSelector(".menu:nth-child(1) > ul > li:nth-child(2) > a > .text")).click();
    // 9 | click | id=logoutButton | 
    driver.findElement(By.id("logoutButton")).click();
  }
}
